### ISSUE TITLE
Update to Kotlin 1.3 and use stdlib Result class

### ISSUE THREAD

**Issue by LouisCAD** [gildor/kotlin-coroutines-retrofit#45]
Even though Retrofit is planning to support `suspend fun` and `Call.await()` natively, it is likely weeks away (per [the PR author words](https://github.com/square/retrofit/pull/2886#issuecomment-433974999)) and one using this library may want to upgrade to 1.3 before.

**Comment by gildor** [comment]
@LouisCAD Yes, thanks to rising this. 
I will update to 1.3 today, but not sure about Result. The problem that existing Result provides more cases than library one. And probably someone uses those features. So I will probably keep existing behavior and deprecate it and provide `awaitCatching()` instead.

**Comment by gildor** [comment]
Version 1.0 of the library available now on JCenter and Maven central.
I decided to not introduce kotlin.Result even as separate library for now, if someone want it's easy just to add such extension function (you also should add required flags to enable kotlin.Result as return type of function):
```
fun Call<T>.awaitCatching() = runCatching { await() }
```

One more reason, I decided do not deprecate or rename `ru.gildor.coroutines.retrofit.Result` because cannot provide typealias to be backward compatible. I do not want to force everyone to migrate, I hope soon Retrofit will get support of coroutines out of the box, so everyone can switch only once
